/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary': '#505f76',
        'on-surface-variant': '#424656',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-container': '#6f7274',
        'surface-bright': '#faf8ff',
        'on-surface': '#131b2e',
        'on-secondary': '#ffffff',
        'outline': '#727687',
        'inverse-surface': '#283044',
        'tertiary': '#565a5b',
        'secondary-fixed': '#d3e4fe',
        'on-tertiary-fixed-variant': '#444749',
        'primary': '#0050cb',
        'primary-fixed-dim': '#b3c5ff',
        'on-tertiary-container': '#f6f8fa',
        'surface-container-high': '#e2e7ff',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#b7c8e1',
        'on-background': '#131b2e',
        'on-tertiary': '#ffffff',
        'surface-tint': '#0054d6',
        'on-primary-fixed': '#001849',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#b3c5ff',
        'secondary-container': '#d0e1fb',
        'on-secondary-fixed': '#0b1c30',
        'on-primary-container': '#f8f7ff',
        'surface': '#faf8ff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'on-secondary-container': '#54647a',
        'surface-container-highest': '#dae2fd',
        'on-primary-fixed-variant': '#003fa4',
        'surface-dim': '#d2d9f4',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#191c1e',
        'surface-container': '#eaedff',
        'on-secondary-fixed-variant': '#38485d',
        'inverse-on-surface': '#eef0ff',
        'error': '#ba1a1a',
        'background': '#faf8ff',
        'surface-variant': '#dae2fd',
        'tertiary-fixed-dim': '#c4c7c9',
        'primary-container': '#0066ff',
        'surface-container-low': '#f2f3ff',
        'primary-fixed': '#dae1ff',
        'outline-variant': '#c2c6d8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        'sidebar-width': '240px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md':    ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'mono-sm':     ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display':     ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
