/**
 * migrate.js — Push schema changes directly to the SQLite DB.
 *
 * Run with:  npm run db:migrate  (from the server workspace)
 *
 * Drizzle's `migrate()` applies SQL migration files from the
 * drizzle/ output folder generated by `drizzle-kit generate`.
 */

import 'dotenv/config';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { db, sqlite } from './client.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const migrationsFolder = path.resolve(__dirname, '../../drizzle');

console.log('🔄 Running migrations from:', migrationsFolder);

migrate(db, { migrationsFolder });
sqlite.close();

console.log('✅ Migrations complete.');
